import os
import pathlib
import sys

REPO_ROOT = pathlib.Path(__file__).parent.parent.parent
sys.path.append(str(REPO_ROOT))

# This script should be careful not to disrupt automatic mechanism which
# may be expecting certain stdout, always print to stderr.
sys.stdout = sys.stderr

from bazel.wrapper_hook.install_modules import install_modules
from bazel.wrapper_hook.wrapper_debug import wrapper_debug

wrapper_debug(f"wrapper hook script is using {sys.executable}")


def main():
    install_modules(sys.argv[1])

    from bazel.wrapper_hook.autogenerated_targets import autogenerate_targets
    from bazel.wrapper_hook.engflow_check import engflow_auth
    from bazel.wrapper_hook.generate_common_bes_bazelrc import write_workstation_bazelrc
    from bazel.wrapper_hook.plus_interface import (
        check_bazel_command_type,
        test_runner_interface,
    )
    from bazel.wrapper_hook.rbe_auth import RbeAuthError, RbeAuthRequired, get_id_token
    from bazel.wrapper_hook.set_mongo_variables import write_mongo_variables_bazelrc

    write_mongo_variables_bazelrc(sys.argv)

    # This is used to autogenerate a BUILD.bazel that creates
    # Filegroups for select tags - used to group targets for installing
    autogenerate_targets(sys.argv, sys.argv[1])

    enterprise = True
    if check_bazel_command_type(sys.argv[1:]) not in [
        "clean",
        "shutdown",
        "version",
        None,
    ]:
        args = sys.argv

        if any(arg.startswith("--include_mongot") for arg in args):
            os.makedirs("mongot-localdev", exist_ok=True)

        write_workstation_bazelrc(args)

        args = test_runner_interface(
            sys.argv[1:],
            autocomplete_query=os.environ.get("MONGO_AUTOCOMPLETE_QUERY") == "1",
            enterprise=enterprise,
        )

        # PSMDB-2043: inject the OIDC bearer for the on-demand RBE
        # buildfarm only when this build actually uses it. We key off
        # `--config=psmdb_buildfarm` (the only config that flips
        # --remote_executor to grpcs://bb-psmdb.ddns.net:8981 — see
        # .bazelrc.psmdb). Local / CI-side EngFlow / public-release
        # builds keep travelling through engflow_auth above and
        # never hit Dex.
        #
        # Refresh / login is driven through `rbe_auth.get_id_token`:
        #   * cached + fresh → zero RTT, append the header, done
        #   * cached + expired with valid refresh_token → silent /token
        #     refresh, then append
        #   * no usable refresh + TTY → Device Code flow on stderr
        #     (URL + user_code), polls Dex /token until login
        #   * no usable refresh + non-TTY (Jenkins, scripted runs)
        #     → fail fast with a pointer to `percona-packaging/scripts/rbe_login.py`. We
        #     deliberately don't inject a stale-or-empty header here:
        #     letting Bazel run the build with no auth would just
        #     produce Envoy 401s on every action and a much noisier
        #     failure than this one.
        if any(a.startswith("--config=psmdb_buildfarm") for a in args) or any(
            a == "--config" and i + 1 < len(args) and args[i + 1] == "psmdb_buildfarm"
            for i, a in enumerate(args)
        ):
            from bazel.wrapper_hook import rbe_auth

            wrapper_debug("rbe_auth: --config=psmdb_buildfarm detected, fetching OIDC token")
            pre = rbe_auth.status()
            wrapper_debug(
                f"rbe_auth: cache before — present={pre.get('present')} "
                f"fresh={pre.get('fresh')} expires_at={pre.get('expires_at', 0)} "
                f"sub={pre.get('subject', '')!r}"
            )
            try:
                token = get_id_token()
            except RbeAuthRequired as e:
                print(f"RBE auth: {e}", file=sys.stderr)
                sys.exit(4)
            except RbeAuthError as e:
                print(f"RBE auth failed: {e}", file=sys.stderr)
                sys.exit(4)
            post = rbe_auth.status()
            wrapper_debug(
                f"rbe_auth: cache after  — present={post.get('present')} "
                f"fresh={post.get('fresh')} expires_at={post.get('expires_at', 0)} "
                f"groups={post.get('groups')}"
            )
            wrapper_debug(
                f"rbe_auth: token bearer={token[:12]}…{token[-6:]} (len={len(token)}); "
                "appending --remote_header / --bes_header authorization to args"
            )
            # Bazel does NOT auto-forward --remote_header into --bes_header:
            # they're separate CLI surfaces driving separate gRPC channels
            # (--remote_executor / --remote_cache vs --bes_backend). PSMDB-2034
            # added a Build Event Stream sink on grpcs://bb-psmdb.ddns.net:1985
            # (Envoy → bb-portal-backend), validated against the same Dex
            # `bazel-cli` audience that gates :8981, so the same JWT works on
            # both — but we have to attach it twice.
            args = list(args) + [
                f"--remote_header=authorization=Bearer {token}",
                f"--bes_header=authorization=Bearer {token}",
            ]
    else:
        args = sys.argv[2:]

    os.chmod(os.environ.get("MONGO_BAZEL_WRAPPER_ARGS"), 0o644)
    with open(os.environ.get("MONGO_BAZEL_WRAPPER_ARGS"), "w") as f:
        f.write("\n".join(args))
        f.write("\n")


if __name__ == "__main__":
    main()
