# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target='audit',
    source=[
        'audit_commands.cpp',
        'audit_flusher.cpp',
        'audit_options.cpp',
        'audit.cpp',
        'audit_parameters.idl',
        'audit_options.idl',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/commands/test_commands_enabled',
        '$BUILD_DIR/mongo/db/matcher/expressions',
        '$BUILD_DIR/mongo/db/pipeline/expression_context',
        '$BUILD_DIR/mongo/idl/server_parameter',
        '$BUILD_DIR/mongo/util/background_job',
    ],
    LIBDEPS_DEPENDENTS=[
        '$BUILD_DIR/mongo/db/commands',
    ],
)
