# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Library(
    target='auditcore',
    source=[
        'audit_options.cpp',
        'audit.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/auth/authcore',
    ],
)

env.Library(
    target='audit',
    source=[
        'audit_commands.cpp',
        'audit_flusher.cpp',
    ],
    LIBDEPS=[
        'auditcore',
        '$BUILD_DIR/mongo/util/background_job',
    ],
    LIBDEPS_DEPENDENTS=[
        '$BUILD_DIR/mongo/db/commands'
    ],
)
