.TH mongos 1
.SH NAME
mongos \- MongoDB Sharded Cluster Query Router

.SH SYNOPSIS
.sp
\fBmongos\fP for "MongoDB Shard," is a routing service for
MongoDB shard configurations that processes queries from the
application layer, and determines the location of this data in the
\fIsharded cluster\fP, in order to complete these operations.
From the perspective of the application, a
\fBmongos\fP instance behaves identically to any other MongoDB
instance.

.SH DESCRIPTION
This manual page has been deprecated.

For a complete list of available options, run:

\fBmongos --help\fP

For full documentation, visit:

\fBhttps://docs.percona.com/percona-server-for-mongodb/9.0/\fP

.SH AUTHOR
Percona and/or its affiliates
