.TH mongod 1
.SH NAME
mongod \- MongoDB Server

.SH SYNOPSIS
.sp
\fBmongod\fP is the primary daemon process for the MongoDB
system. It handles data requests, manages data access, and performs
background management operations.

.SH DESCRIPTION
This manual page has been deprecated.

For a complete list of available options, run:

\fBmongod --help\fP

For full documentation, visit:

\fBhttps://docs.percona.com/percona-server-for-mongodb/9.0/\fP

.SH AUTHOR
Percona and/or its affiliates
